using E_commerce_App_Web.IRepositories;
using E_commerce_App_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace E_commerce_App_Web.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CustomerController : ControllerBase
    {
        private readonly ICustomerRepository _customerRepository;

        public CustomerController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }
            
        // GET: api/Customer/by-email?email=someone@site.com
        [HttpGet("by-email")]
        public async Task<IActionResult> GetByEmail([FromQuery] string email)
        {
            if (string.IsNullOrWhiteSpace(email))
                return BadRequest("Email is required.");
            var emailValidator = new EmailAddressAttribute();
            if (!emailValidator.IsValid(email))
                return BadRequest("Email is not a valid email address.");

            var customer = await _customerRepository.GetByEmailAsync(email);
            if (customer == null)
                return NotFound("Customer not found.");

            return Ok(customer);
        }

        // GET: api/Customer/{id}
        [HttpGet("{id}")]
        public async Task<IActionResult> GetById([FromRoute] string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return BadRequest("Customer id is required.");

            var customer = await _customerRepository.GetByIdAsync(id);
            if (customer == null)
                return NotFound("Customer not found.");

            return Ok(customer);
        }

        // GET: api/Customer/{id}/profile
        // "Heavy" query: cart + products, favorites + products
        [HttpGet("{id}/profile")]
        public async Task<IActionResult> GetProfileWithDetails([FromRoute] string id)
        {
            if (string.IsNullOrWhiteSpace(id))
                return BadRequest("Customer id is required.");

            var customer = await _customerRepository.GetProfileWithDetailsAsync(id);
            if (customer == null)
                return NotFound("Customer not found.");

            return Ok(customer);
        }

        // POST: api/Customer
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] Customer customer)
        {
            if (customer == null)
                return BadRequest("Customer payload is required.");

            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            var created = await _customerRepository.AddAsync(customer);

            // If Id is generated by HiLo/EF, it should be available after SaveChangesAsync().
            return CreatedAtAction(nameof(GetById), new { id = created.Id, name = created.UserName }, created);
        }

        // PUT: api/Customer/{id}
        [HttpPut("{id}")]
        public async Task<IActionResult> Update([FromRoute] string id, [FromBody] Customer customer)
        {
            if (string.IsNullOrWhiteSpace(id))
                return BadRequest("Customer id is required.");

            if (customer == null)
                return BadRequest("Customer payload is required.");

            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            var updated = await _customerRepository.UpdateAsync(id, customer);
            if (updated == null)
                return NotFound("Customer not found.");

            return Ok(updated);
        }

        // POST: api/Customer/{id}/favorites/{productId}
        [HttpPost("{id}/favorites/{productId:int}")]
        public async Task<IActionResult> AddFavoriteProduct([FromRoute] string id, [FromRoute] int productId)
        {
            if (!ModelState.IsValid)
                return ValidationProblem(ModelState);

            try
            {
                var favorite = await _customerRepository.AddFavoriteProductAsync(id, productId);
                return Ok(favorite);
            }
            catch (ArgumentException ex)
            {
                return BadRequest(ex.Message);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ex.Message);
            }
            catch (InvalidOperationException ex)
            {
                return Conflict(ex.Message);
            }
        }

    }
}
